### PR TITLE
add trf

### PR DESCRIPTION
**Pull request by FernandezMathieu**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
Good find, but probably blocked:

```
ValueError: [E002] Can't find factory for 'transformer' for language English (en). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).
```

a brief dance with `grayskull` suggests we'd need `spacy-transformers` and `spacy-alignments` (which has a `rust` dependency). Thoughts, @conda-forge/spacy?

**Comment by adrianeboyd** [comment]
When spacy v3.0.0 was released there were gaps in some of the conda-forge dependencies for transformers (`sentencepiece`, I think?), so we didn't pursue this, but I think that's improved in the last year and we can have another look. If the rust dependency is not too difficult to manage, we wouldn't be opposed to adding conda-forge packages for `spacy-transformers` and `spacy-alignments`.

**Comment by setu4993** [comment]
Thanks @adrianeboyd! We added support for `sentencepiece` and `transformers` to conda-forge a few months ago across all OSes, so they should be easy to integrate.

**Comment by setu4993** [comment]
The [`tokenizers` feedstock](https://github.com/conda-forge/tokenizers-feedstock/) uses rust, in case that's useful for inspiration.

**Comment by bollwyvl** [comment]
No worries, was just reporting my findings... not looking to sign anybody up for anything! It all sounds doable, and there are numerous `setuptools-rust` examples out there. Happy to help review, but it's a little out of scope for me to take on at the moment!

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@FernandezMathieu @conda-forge/spacy-transformers @conda-forge/spacy-alignments thanks all!

**Pull request merged**
