### PR TITLE
Update to v2.2.0

### PR DESCRIPTION
**Pull request by setu4993**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by setu4993** [comment]
@conda-forge/spacy-model-en_core_web : This PR is ready for review.

**Comment by bollwyvl** [comment]
Thanks, @setu4993, LGTM, and always happy for the maintainers! @sodre?

**Review by bollwyvl — APPROVED** [review]

**Comment by bollwyvl** [comment]
I'd love to know how we could get the bot to propose these in the future...

**Comment by setu4993** [comment]
@bollwyvl : I think the reason the bot can't propose updates is because of the nested folder structure. It would be easier to split the 3 model sizes into their own repos which the bot could then source directly from the releases.

**Comment by setu4993** [comment]
@bollwyvl : Just noticed the license on the models is [MIT](https://github.com/explosion/spacy-models/blob/master/meta/en_core_web_sm-2.2.0.json), not CC. I changed the license to MIT and sourced it from the spaCy repo.

**Comment by bollwyvl** [comment]
> the license on the models

Very good catch! Rather odd state of affairs, to be sure. We should likely upstream a request to get it added a little bit more concretely.

>  easier to split the 3 model sizes into their own repos 

There are a number of feedstock with multiple inputs, and more repos are just more things to keep in sync. I think the bigger issue is the variants. While "cleaner", i think the bot prefers everything be done in jinja syntax. We might be able to grab a single canary file, like the meta, and drive somthing off that.

**Pull request merged**
