### PR TITLE
Split outputs

### PR DESCRIPTION
**Pull request by setu4993**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bollwyvl** [comment]
This is looking promising!

Here's an issue in the bot repo (a little hard to find) that has some pointers about where to look for things:
https://github.com/regro/cf-scripts/issues/653#issuecomment-542226903

Basically, we'd want to:
- fully prepare an older verison
- fully prepare a newer version
- put them in a case in https://github.com/regro/cf-scripts/blob/master/tests/test_migrators.py

I'm happy to do check it out once you think it's mostly in working order.

The duplication of the outputs _could_ be a `{% for %}` loop... but this is usually frowned upon, and is indeed why `conda_build_config` is far superior... hence why it might be nice to figure out how to get this into the bot properly, as it seems like a likely pattern for future data-driven packages.

The alternative canary idea is we pick _one_ file (for bot reasons, probably must be listed _first_) that we know will change based on the version, e.g. `meta/en_core_web_lg-{{ version }}.json` and then leave the rest of the recipe as is, and don't do anything with the canary file. We'll _still_ have to download the files to calculate the shasums... or trust CI to do it, which I would be tempted to do with the massive files. But conda build will happily take care of the rendering of the multiple variants.

Very sorry it's all a bit confusing, and `xonsh` doesn't help, but it's the best we have, today:
https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators.xsh#L451

**Comment by setu4993** [comment]
Sorry, but I don't think I follow all the other steps that are / would be involved. This seems to work and pass tests correctly for the current version, which inspires my confidence in this approach. It intuitively makes sense to me that we'd want to create a similar config for an older version and test out if the bot picks it up (and that's what we use the `test_migrators` for).

Forgive my lack of experience here, all the packages I have encountered and helped with were `pypi` sourced, which made the bot integrations easy.

#3

**Comment by bollwyvl** [comment]
Yeah, this is a weird package. If you think it's looking good, I'll take a
look in the bot test harness.

**Comment by setu4993** [comment]
I think it's in a good place to test if it actually does the updates to newer versions. If you know ways to test it, I can help with them.

**Comment by bollwyvl** [comment]
Ack, just saw this! I'll fire it up in the bot presently...

**Comment by bollwyvl** [comment]
Yeah, looks good: I did have to replace all of the `{{ sm }}`, etc. with the literal string. Finish up the TODOs (build number and license) and this is probably good to go.

**Comment by setu4993** [comment]
Great! I'll fix those and push out an update in a few.

**Comment by setu4993** [comment]
Done!

**Comment by setu4993** [comment]
Bump.

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
Let's give it  try

**Pull request merged**
